CREATE DATABASE images.db;

CREATE TABLE IMAGE(
    ID INT PRIMARY KEY NOT NULL,
    NAME VARCHAR(42) NOT NULL,
    SRC BLOB NOT NULL,
    INSERT_TS DATETIME NOT NULL
);

CREATE TABLE IMAGE_TAG(
    ID INT PRIMARY KEY NOT NULL,
    IMG_ID INT NOT NULL,
    TAG_NAME VARCHAR(20) NOT NULL,
    INSERT_TS DATETIME NOT NULL,
    FOREIGN KEY(IMG_ID) REFERENCES IMAGE(ID)
);

--sqlite> INSERT INTO IMAGE (ID, NAME, SRC, INSERT_TS) VALUES (1, 'my_img', 'some_src', '2021-04-24 00:00:00.000');
--sqlite> INSERT INTO IMAGE_TAG (ID, IMG_ID, TAG_NAME, INSERT_TS) VALUES (1, 1, 'dog', '2021-04-24 00:00:00.000');