name:                object-detectifier
version:             0.1.0.0
github:              "KaylaHood/object-detectifier"
license:             BSD3
author:              "Kayla Hood"
maintainer:          "kaylahood1996@gmail.com"
copyright:           "Copyright © 2021 H‑E‑B, LP"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Artificial Intelligence

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/KaylaHood/object-detectifier#readme>

dependencies:
- base >= 4.7 && < 5
- warp
- wai
- http-types
- gogol
- gogol-vision
- HDBC-sqlite3
- HDBC

library:
  source-dirs: src

executables:
  object-detectifier-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - object-detectifier

tests:
  object-detectifier-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - object-detectifier
